{admin: true, api_token: aecd74b56426830aceb5a3d6130efc5e, at: '2017-11-18T01:32:57+00:00',
  default_currency: USD, default_hourly_rate: 0, ical_enabled: true, id: 2269520,
  name: Xander's workspace, only_admins_may_create_projects: false, only_admins_see_billable_rates: false,
  only_admins_see_team_dashboard: false, premium: false, profile: 0, projects_billable_by_default: true,
  rounding: 0, rounding_minutes: 0}
