---
language: python
sudo: required
cache:
  pip: 'yes'
before_script:
  - sudo pip install virtualenv 
  - virtualenv -p /usr/bin/python3 .py
  - .py/bin/pip install pytest
  - .py/bin/pip install nose
  - .py/bin/pip install -e modules/humanresources
script:
  - pytest || true
  - cd modules/humanresources
  - pytest || true
  - nosetests -s -d -v
...
# vim: ft=ansible:
