---
language: python
sudo: required
cache:
  pip: 'yes'
before_script:
  - sudo pip install virtualenv 
  - virtualenv -p /usr/bin/python3 .py
  - .py/bin/pip install pytest
  - .py/bin/pip install nose
script:
  - pytest || true
  - cd addons/google_drive/models/tests
  - python -m unittest test_google_drive 
...
# vim: ft=ansible:
